version: '3.7'

services:

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer:4
    ports:
      - 8081:8080

  app:
    build: ./app
    ports:
      - 8080:80
    volumes:
      - ./app/src:/var/www/html
    env_file: .env
    depends_on:
      - db

volumes:

  db_data:
